/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'CyberryPotter' 
 * Target:  'Target 1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* tensorflow::Machine Learning:TensorFlow:Kernel&CMSIS-NN@1.23.2 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
